# Generated by Django 3.0.3 on 2020-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='price_total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
    ]
