# Generated by Django 3.0.3 on 2020-03-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200311_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
