# Generated by Django 3.0.3 on 2020-03-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200317_0225'),
        ('orders', '0007_auto_20200312_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество товаров')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена товара')),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Полная цена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимость')),
                ('session_key', models.CharField(default=0, max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
