# Generated by Django 3.0.3 on 2020-03-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200317_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Категория'),
        ),
    ]
