# Generated by Django 3.0.3 on 2020-03-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200317_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ProductCategory',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
    ]
