# Generated by Django 3.0.3 on 2020-03-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200317_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='category',
        ),
    ]
